@startmindmap

* 案例讨论
	* 铅中毒
		* 铅吸收途径
			* 消化道
			* 呼吸道
		* 临床表现
			* 消化道症状
				* 腹绞痛
				* 腹泻
				* 呕吐
			* 神经系统
				* 烦躁
				* 铅垂腕
				* 头痛
				* 头晕
			* 血液系统
				* 血红蛋白合成减少
		* 治疗
			* 急性
				* 脱离暴露环境
				* 催吐
				* 导泻
				* 胃肠解痉：葡萄糖酸钙
			* 慢性
				* 异地酸二钠：去铅
		* 分级
			* 轻度
			* 中度
				* 腹绞痛
				* 贫血
			* 重度
				* 中毒性脑病
		* 机制
			* 影响血红蛋白的合成
		* 诊断
			* FEP
			* ZPP
			* δ-ALA
		* 生活中铅来源
			* 玩具
			* 油漆
			* 彩釉
			* 爆米花
			* 松花蛋
			* 汽油防爆剂
		* 血铅正常值
			* 儿童：&lt; 100 μg
			* 成人：&lt; 400 μg
		* 铅对儿童健康的影响
		* 预防
			* 健康教育
			* 取缔高污染工厂
			* 体检筛查
			* 早发现早治疗

left side

	* 铅污染
		* 中毒原因：该工厂铅粉尘超标
		* 防治措施
			* 政策措施
				* 建厂前进行职业卫生预评价
				* 建厂前进行职业危害评价
				* 建厂前进行安全性评价
				* 建厂开工后进行控制效果评价
				* 建厂后进行日常检测评价
			* 厂内措施
				* 改良工艺
				* 使用特殊防尘口罩
				* 配备洗涤用品与淋浴设施
				* 进行封闭生产
				* 空气除尘处理
			* 管理措施
				* 员工定期体检
				* 定期监测粉尘浓度
				* 健康教育
				* 加强营养
		* 如何诊断职业性铅中毒
			* 有铅接触史
			* 职业场所检查
			* 有临床症状
			* 有检查证据

@endmindmap
