NODEENTRY := "index.js"

clean:
	fd "\.csv$" -x rm {}

# Provided FILENAME (without extension), convert the yaml file into anki-compatible csv file
standard2csv:
	yq -r ".[] | [.UUID, .F, .B] | @csv" standard.yaml > standard.csv

table:
	node {{NODEENTRY}}
