graph LR
        dc(动眼神经核)
        df(动眼神经副核)
        h(滑车神经核)
        sz(三叉神经中脑核)
        sn(三叉神经脑桥核)
        sj(三叉神经脊束核)
        sy(三叉神经运动核)
        z(展神经核)
        m(面神经核)
        sx(上泌涎核)
        xx(下泌涎核)
        y(疑核)
        f(副神经核)
        g(孤束核)
        mb(迷走神经背核)
        s(舌下神经核)
        w(蜗神经核)
        q(前庭神经核)

        i(嗅神经)
        ii(视神经)
        iii(动眼神经)
        iv(滑车神经)
        v(三叉神经)
        vi(展神经)
        vii(面神经)
        viii(前庭蜗神经)
        ix(舌咽神经)
        x(迷走神经)
        xi(副神经)
        xii(舌下神经)

    dc-->iii
    df==>iii
    h-->iv
    v-->sn
    v-->sj
    v-->sz
    sy-->v
    z-->vi
    m==>vii
    sx==>vii
    w==>viii
    q==>viii
    y==>ix
    xx==>ix
    ix==>g
    ix-->sj
    mb-->x
    ix==>g
    y==>x
    x-->sj
    f==>xi
    s-->xii
