OUTPUT := "output.csv"

clean:
	rm *.csv || true

convert_all: clean
	@for f in `ls *.yaml | cut -d. -f1`; do \
		echo "Converting \"${f}\".yaml to \"${f}.csv\"";\
		just _convert_csv "${f}";\
	done
	just _markdown_to_html

# Provided FILENAME (without extension), convert the yaml file into anki-compatible csv file
_convert_csv FILENAME:
	yq -r ".[] | [.UUID, .cloze, .created_time, \"{{FILENAME}}\"] | @csv" "{{FILENAME}}.yaml" >> "{{OUTPUT}}"

_markdown_to_html:
	#!/usr/bin/env python
	import markdown
	import pandas as pd
	from functools import partial
	import re

	INLINE_MATH_RE = re.compile(r"(?<!\\)\$([^\$]+)\$")
	BLOCK_MATH_RE = re.compile(r"(?<!\\)\$\$([^\$]+)\$\$")
	markdownfn = partial(
		markdown.markdown,
		extensions=['tables', 'fenced_code'],
	)

	def mapfn(text):
		text = markdownfn(text)
		text = BLOCK_MATH_RE.sub(r"\\[\1\\]", text)
		text = INLINE_MATH_RE.sub(r"\\(\1\\)", text)
		return text

	df = pd.read_csv("./{{OUTPUT}}", names=["UUID", "cloze", "created_time", "tag"])
	df.cloze = df.cloze.map(mapfn)
	df.to_csv("./{{OUTPUT}}", header=False, index=False)
