clean:
	fd "\.csv$" -x rm {}

# Provided FILENAME (without extension), convert the yaml file into anki-compatible csv file
points2csv:
	yq -r ".[] | [.UUID, .Q, .A, .tags] | @csv" points.yaml > points.csv
	just _markdown_to_html points

_markdown_to_html FILENAME:
	#!/usr/bin/env python
	import markdown
	import pandas as pd
	df = pd.read_csv("./{{FILENAME}}.csv", names=["UUID", "Q", "A"])
	df.A = df.A.map(markdown.markdown)
	df.to_csv("./{{FILENAME}}.csv", header=False, index=False)
