clean:
	fd "\.csv$" -x rm {}

points2csv:
	yq -r ".[] | [.UUID, .Q, .A, .tags] | @csv" points.yaml > points.csv
	just _markdown_to_html points

_markdown_to_html FILENAME:
	#!/usr/bin/env python
	import markdown
	import pandas as pd
	from functools import partial

	df = pd.read_csv("./{{FILENAME}}.csv", names=["UUID", "Q", "A", "tags"])
	df.A = df.A.map(partial(markdown.markdown, extensions=['markdown.extensions.tables']))
	df.to_csv("./{{FILENAME}}.csv", header=False, index=False)
