@startuml
left to right direction

frame 内环 {
    card 腺样体
    card 腭扁桃体
    card 舌扁桃体
}

frame 外环 {
    card 咽后淋巴结
    card 下颌角淋巴结
    card 颌下淋巴结
    card 颏下淋巴结
}

腺样体-->咽后淋巴结
腺样体-->下颌角淋巴结
舌扁桃体-->颏下淋巴结
颏下淋巴结-->颌下淋巴结
颌下淋巴结-->下颌角淋巴结
舌扁桃体-->下颌角淋巴结
腭扁桃体-->下颌角淋巴结

@enduml
